name: ${project.name}
main: io.github.archemedes.betterbooks.BetterBooks
version: ${project.version}
description: ${project.description}
depend: [Tythan]
softdepend: [Omniscience, RPPersonas]
api-version: 1.13

commands:
  signbook:
    description: Changes the author of a written book
    usage: /signbook [author name]
  browsebook:
    description: Browse to the page of a book you are reading
    usage: /browsebook [page number]
  